### ISSUE TITLE
邻接矩阵是手动算出来的嘛？

### ISSUE THREAD

**Issue by aicha0910** [WangHelin1997/AT-GCN#1]
audioset_ba_adj.pkl  比如这个文件在哪？是怎么计算出来的？
感谢解答！

**Comment by dby124** [comment]
作者您好，最近拜读了您在IEEE Signal Processing Letters上发表的论文《Modeling label dependencies for audio tagging with graph convolutional network》，我们对您的这项工作十分感兴趣，我们下载了您在论文中开源的代码，但是代码运行过程中出现了文件缺失问题，具体如下：
1. train.py中，缺失了邻接矩阵（audioset_ba_adj.pkl）和归一化的文件（checkpoint199.pt ）
2. util_in.py中，缺失normalizer.pkl

不知您是否方便，共享这几个文件呢，以便我们复现您的工作。
冒昧联系，感谢您阅读并期待您的回复。
